application: ###appname###
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /runtask
  script: main.app
  login: admin

- url: /daily
  script: main.app
  login: admin

- url: /manual
  script: main.app
  login: required

- url: /dbg
  script: main.app
  login: required

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest